---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src/workspace/shwezin

steps:
  - name: lint
    image: python:3.7-alpine
    commands:
      - python -m pip install -r requirements.txt
      - flake8
